name: Deploy Repo Rules
 
on:
  push:
    branches: [ main ]
 
  workflow_dispatch:
 
permissions:
  id-token: write
  contents: read

env:
  FUNCTION_NAME: github-repo-rules
  SCRIPT_PATH: '.'
  RESOURCE_GROUP: github-repo-rules
  LOCATION: 'eastus'
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy Azure Function
      uses: Azure/functions-action@v1.1.8
      with:
        app-name: ${{ env.FUNCTION_NAME }}
        package: ${{ env.SCRIPT_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
